# Generated by Django 5.2.4 on 2025-07-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the note', max_length=200)),
                ('content', models.TextField(help_text='Enter the content of the note')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the note was last updated')),
            ],
        ),
    ]
