# Generated by Django 5.2.4 on 2025-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes for the note'),
        ),
    ]
